    A Taste of Honey - Boogie Oogie Oogie         (funk groovy)
    Alfonse Mouzon - Funky Snakefoot			  (funk instu)
    Andreda True Connection - What's Your Name	  (disco funky)
    Air - Sexy Boy        (athmosphérique)
    Air France - June evenings (calme)
    Arcade Fire - Everitything Now				  (pop-rock upbeat)
    Azymuth - Jazz Carnival		(jazz funk instru)
    Blow - Power		(posé groovy)
    Bon Voyage Organisation - [G Comme] Géographie		(posé groovy indé pop fr)
    Bon Voyage Organisation - Schenzen V			(indé pop fr groovy)
    Breakbot - Baby I'm Yours
    Breakbot - Fantasy (feat. Ruckazoid)        (groove, slow bpm)
    Breakbot & Yasmin - "My Toy"    (groovy happy)
    Breakbot - Mystery        (groovy basses)
    Breakbot - One Out Of Two (feat. Irfane)        (groove tranquille)
    Breakbot - Programme        (groove catchy tranquille)
    Breakbot - Why? (feat. Ruckazoid)        (groove tranquille)
    Broken Bells - After the Disco			(pop groovy)
    Bruno Mars - Treasure    (groovy)
    C2C - Arcades     (poum tchach scratch)
    C2C - Genius (feat. Gush)   (upbeat)
    Cerrone - Bodytalk			(disco groove instru)
    Cerrone - Give me Love (Edit)    (disco groovy)
    Cerrone - Hooked on You [The Reflex Revision]			(disco posée un peu groovy)
    Cerrone V - Call Me Tonight     (disco enivrante un peu longue)
    Change - This Is Your Time		(disco funk dansante)
    Chic - Le Freak         (disco groovy)
    Chic - Good Time     (disco tranquille feel good)
    Chic - I Want Your Love            (disco funk tranquille)
    Chic - Soup For One 				(post-disco tranquille riff de Modjo Lady)
    Chilly - For Your Love 				(remix funk rock)
    Cory Wong - Work It Out (feat. Antwaun Stanley)        (funk tranquille moderne)
    Charles Earland - Cornbread 			(funk groovy instru)
    Cranston Dean - I Got The Shakes        (groove bluesy)
    Chromeo - Over Your Shoulder            (pop funky)
    Daft Punk - Get Lucky                    (funky)
    Daft Punk - Give Life Back to Music        (groovy electro)
    Daft Punk - Lose Yourself to Dance        (funk qui va bien)
    Deodato - Keep On Movin'        (funk bien gras)
    Earth Wind & Fire - Let's Groove            (groove funky)
    Eckhardt And The House - If You Cannot Talk		(pop tranquille funky nu disco)
    Edwin Birdsong - Cola Bottle Baby 			(disco funk riff Harder better[...])
n   Electro Deluxe - Sleepwalking               (nu disco goovy) 
    Elephanz - Curfew				(posé popouille groovy)
    Empire Of The Sun - Walking On A Dream     (pop groove tranquille)
n   Escort - Cocaine                        (funk rock dansant) 
    Fat Larry's Band - Act Like You Know    (funk fever 105)
    Franc Moody - Dopamine					(poom-tchack très groovy)
    Fred Falke - 808 PM at the Beach		(instru nu-funky )
    Foals - My Number     (pop  post rock qui bouge)
    Fort Knox Five - 
    Gaz - Cantina Band					(disco sauce Star Wars)
    George Benson - Give Me The Night    (funk dançant)
    George Duke - Reach Out                (disco funky)
    Giorgio Moroder - Knights in White Satin		(disco posé)
    Giorgio Moroder - Sooner or Later		(disco groovy)
    Goose - Real (Moonlight Matters Remix)			(presque edm catchy)
    half•alive - still feel.			(pop indé fin upbeat)
    Hot Chip - Thieves in the Night    (happy sauce 80)
    Hot Chocolate - Dance (Get Down to it)			(groovy un peu kitch)
    Hypnolove - La piscine (Voilaaa Remix)            (nu disco fr posé)
n   Hypnolove - La piscine (L'Impératrice Remix)    (groovy electro-funky nu disco)
    Joss Stone - Super Duper Love        (soul funky)
    Jamiroquai - Virtual Insanity		 (groovy posé)
n   Juice - Lizzo                   (façon disco dansant)
    Justice - Safe and Sound       (grosses basses)
    Justice - Stop					(french touch aérien)
    Kakkmaddafakka - Your Girl		(pop upbeat)
    Keedz - Stand on the World (Mimma Remix)        (commercial sauce french touch)
    Kleeer - Open Your Mind				(funk posé)
    Kool & The Gang - Get Down On It      (groove tranquille)
    Kool & The Gang - Ladies Night          (disco groovy)
    L'impératrice - Matahari                        (groove sautillant)
    L'impératrice - Matahari (le retour)            (groove sautillant instru)
    L'impératrice - Séquences (Parcels Remix)        (groove tranquille)
    L'impératrice - Sonate Pacifique  				(tranquille aérien crescendo)
    L'impératrice - Odyssée        (instru groove)
    Lifelike - So Electric (Roller Disco Edit)    (goove instru 80)
    M83 - Midnight City    (pop tranquille)
    Mark Ronson - Valerie        (soul upbeat)
n   Naïve New Beaters - Addicted To Joy             (chill funk nu disco)
    Masayoshi Takanaka - Sexy Dance		(instru funky posé upbeat)
    Mcfadden & Whitehead - Ain't No Stoppin' Us Now     (disco groovy posé)
    Men At Work - Down Under    (80's)
    Metronomy - The Bay        (groovy bass)
    Miami Horror - Sometimes   (pop groove)
    Miami Horror - Echoplex   (pop happy)
n   Mind Enterprises - S.H.A.K.E (breakbot remix)           (groove électro tranquille) 
    Minuit - Paris tropical (Jean Tonique Remix)			(groove posé français)
    MGMT - Electric Feels   (pop groove)
    MGMT - Kids    (pop upbeat)
    MFSB - Sexy		(Funky intru sautillant)
n   Modest Mouse - Lampshades on Fire                       (brit rock groovy)
    Nile Rodgers - State of Mine (it's About Time)			(prosé groovy disco)
    Number One Ensemble - Back To Heaven					(italo disco groovy)
    Pacific - Runaway to Elsewhere (breakbot remix)        (electro groove façon daft punk tranquille)
    Parcels - Lightenup		(groove tranquille)
    Parcles - Older         (chill upbeat)
    Parcels - Overnight            (groove tranquille)
    Parcles - Tieduprightnow		(groove sautillant)
    Parov Stelar - All Night          (Electro Swing dansouille)
    Parov Stelar - Booty Swing     (presque dancefloor)
    Phoenix - If I ever feel better        (pop upbeat sauce french touch)
    Phoenix - Trying To Be Cool (Breakbot Remix)    (pop saveur goovy)
n   PhoMeme - The Less I Know the Sexy Back         (remix groovy de Tame Impala) 
    Poom - Les Voiles			(groovy posé)
    Poom - Qui es-tu ?			(groovy popouille)
    PONY PONY RUN RUN - HEY YOU   (pop upbeat)
    Pnau - Baby (Breakbot Remix)        (chill, groovy)
    Oliver Cheatham - Get Down Saturday Night    (groove fever 105)
    Randy Crawford - Street Life 		(soul funky)
    Ratatat - Abrasive    (très catchy)
    Ratatat - Cream on Chrome (bien groove, mélodie presque agressive)
    Ratatat - Shempi   (catchy upbeat)
    Rjd2 - Ghostwriter        (instru ambiance groove, un peu mou)
    Rock Candy Funk Party - Don't Even Try it        (funk upbeat)
    Royksopp - Happy up here (Breakbot mix)          (groove tranquille un peu répétitif)
    Saint Etienne - Dive		(groove alternance posé et dansant)
n   Saint Motel - My Type       (upbeat) 
    SANTIAGO - Mr love        (bon funk d'époque rythmé)
    Sheila & B. Devotion - Your Love is Good (Dimitri From Paris Remix)			(disco bien funky)
    Sister Sledge - Lost in music (Dimitri from Paris remix)        (disco bon goove)
    Sister Sledge - Thinking Of You (Dimitri from Paris remix)		(disco un peu poom-tchack mais funky)
n	Soul Shaker - Foxxy Knoxxy (Part 1)					(funky passage hip-hop)
    Steve Monite - Things Fall Apart	(funk nigérian)
    Steve Watson - Born to Boogie		(funk groovy)
    Stevie Wonder - Superstition        (groove funk)
    Stretch - Why Did You Do It         (funk tranquille)
    T-Connection - Do What You Wanna Do				(Disco funky)
    Tame Impala - The Less I Know the Better		(poom tchack posé)
    Tatsuro Yamashita - Daydream		(city pop instru bien funky)
    Tatsuro Yamashita - Hot Shot        (groove japonais)
    The Jacksons - Blame It on the Boogie        (groove MJ)
n   The Haggis Horns - Return of the Haggis      (groove funk instru)
    The Rhythm Method - Something For The Weekend				(grovy un peu rnb)
    The Whispers - And the Beat Goes On            (funky groovy)
    The Whitest Boy Alive - 1517			(brit poprock funky)
n   Tom Misch - Disco Yes                   (posé disco dansant)  
    Tuxedo - 2nd Time Around			(funk disco)
    Two Door Cinema Club - What You Know             (poprock sautillante)
    TWRP - The No Pants Dance     (feat. Ninja Sex Party)
    Vitalic - Poison Lips   (presque edm groove)
    VULFPECK - Outro		(instru jazzy funky)
    William Onyeabor - Fantastic Man    (groove summer electronica)
    Yuji Toriyama & Ken Murimura - Night Together        (funk grosses guitares)
